Pipes rewrite
crs4/pydoop pull request #328
Opened 2018-10-15 07:52 UTC by simleo

Fixes #268.
Fixes #269.
Fixes #319.

TODO: update this description.

2018-10-18 13:46 UTC, elzaggo requested changes
It is a definitely major improvement and clean-up of the code base.
One nitpick, thus far :-).
I have the impression that the TaskContext.__cache management could produce unexpected results if the emitted data is changed after the emit call. See the following, admittedly contrived, example:
``` python
foo = {}
class Mapper(api.Mapper):
   def map(self, ctx):
       foo.clear()
       foo[ctx.key] = ctx.value
       ctx.emit(user, foo)
```
I suspect that all the elements of  `.__cache` will all be references the last update of `foo`.

I suggest that we document this behavior and let users deepcopy their data if they really want to do something weird like that.

2018-10-19 12:01 UTC, simleo commented
@elzaggo yes. More generally, using mutable types with a combiner is asking for trouble. Documented in 149aa06

2018-10-19 12:32 UTC, elzaggo approved these changes

2018-10-19 12:33 UTC, elzaggo commented
Approved.

2018-10-19 12:48 UTC, merged